name: Android CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
      - name: Setup JDK
        uses: actions/setup-java@2.3.1
        with:
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build APK
        uses: actions/upload-artifacts@v2.2.4
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
