name: Android CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
      - name: Setup JDK
        uses: actions/setup-java@1.4.2
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build
      - name: Build APK
        uses: actions/upload-artifacts@v2.1.4
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk